import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });
import Cart from "@/components/cart/Cart";
import ReduxProvider from "@/redux/provider";
import RouteChangeListener from "./route-change-listener";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-sans max-w-screen-2xl mx-auto box-border">
        <ReduxProvider>
          <RouteChangeListener />
          <Navbar />
          <div>
            <Cart />
            {children}
          </div>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
